/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishDate' : Time,
  'tags' : Array<string>,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface BookingRequest {
  'id' : string,
  'status' : string,
  'whatsapp' : string,
  'fullName' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'serviceId' : string,
}
export interface PortfolioItem {
  'id' : string,
  'stylingExplanation' : string,
  'title' : string,
  'isPublished' : boolean,
  'fashionTips' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
}
export interface Service {
  'id' : string,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'price' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], undefined>,
  'createPortfolioItem' : ActorMethod<[PortfolioItem], undefined>,
  'createService' : ActorMethod<[Service], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deletePortfolioItem' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'getActiveServices' : ActorMethod<[], Array<Service>>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getBlogPostById' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioItemById' : ActorMethod<[string], [] | [PortfolioItem]>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPublishedPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingRequest' : ActorMethod<[BookingRequest], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string, string, string], undefined>,
  'toggleBlogPostPublish' : ActorMethod<[string, boolean], undefined>,
  'togglePortfolioItemPublish' : ActorMethod<[string, boolean], undefined>,
  'toggleServiceActive' : ActorMethod<[string, boolean], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateBookingRequestStatus' : ActorMethod<[string, string], undefined>,
  'updatePortfolioItem' : ActorMethod<[PortfolioItem], undefined>,
  'updateService' : ActorMethod<[Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];