/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishDate' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Text,
  'stylingExplanation' : IDL.Text,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'fashionTips' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'price' : IDL.Text,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'whatsapp' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'serviceId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [], []),
  'createPortfolioItem' : IDL.Func([PortfolioItem], [], []),
  'createService' : IDL.Func([Service], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Text], [], []),
  'deleteService' : IDL.Func([IDL.Text], [], []),
  'getActiveServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllBookingRequests' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getBlogPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioItemById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PortfolioItem)],
      ['query'],
    ),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getPublishedPortfolioItems' : IDL.Func(
      [],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookingRequest' : IDL.Func([BookingRequest], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'toggleBlogPostPublish' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'togglePortfolioItemPublish' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleServiceActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateBookingRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePortfolioItem' : IDL.Func([PortfolioItem], [], []),
  'updateService' : IDL.Func([Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishDate' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Text,
    'stylingExplanation' : IDL.Text,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'fashionTips' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'price' : IDL.Text,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'whatsapp' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'serviceId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [], []),
    'createPortfolioItem' : IDL.Func([PortfolioItem], [], []),
    'createService' : IDL.Func([Service], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Text], [], []),
    'deleteService' : IDL.Func([IDL.Text], [], []),
    'getActiveServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllBookingRequests' : IDL.Func(
        [],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getBlogPostById' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioItemById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PortfolioItem)],
        ['query'],
      ),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getPublishedPortfolioItems' : IDL.Func(
        [],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookingRequest' : IDL.Func([BookingRequest], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'toggleBlogPostPublish' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'togglePortfolioItemPublish' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleServiceActive' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateBookingRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePortfolioItem' : IDL.Func([PortfolioItem], [], []),
    'updateService' : IDL.Func([Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };